### ISSUE TITLE
You method return me error 400 bad request

### ISSUE THREAD

**Issue by LorenzoTecnab** [WhileTrueThenDream/WebhookIFTTT_arduinoMkr1010Wifi#1]
Hi, i read your solution for send email by event but when in the monitor of my mkr1010 i read bad request (error 400) when 
run my trigger to IFTTT 

this is monitor output.
maker.ifttt.com: 443
GET /trigger/filtro/with/key/(Here i put my key)?value1=55&value2=&value3=Attenzione Allarme Arduino!!! HTTP/1.1
Host: maker.ifttt.com

HTTP Response:
HTTP/1.1 400 Bad Request
Date: Fri, 02 Apr 2021 16:12:46 GMT
Transfer-Encoding: chunked
Connection: close
Server: web_server

Can you help me?

**Comment by WhileTrueThenDream** [comment]
Hi. ​

The error is returned by the server, not by the methode. 
The reason is probably following: The sent http Get request is different from the http Get request  that IFTTT server expects... 

You can check what you configured in your IFTTT and what Get  request is expected by the server and compare it to the Get request that you uare really sending. 

Regards

**Comment by LorenzoTecnab** [comment]
Thx, you are right the problems was on the variable (value1, value2...etc)
